import streamlit as st
import os
import sqlite3
import pandas as pd
import requests
import json

st.set_page_config(page_title="Recallspection Command Centre", layout="wide", page_icon="🧠")

# --- CONFIGURATION ---
# Point these to your actual persistent paths and API
API_BASE_URL = os.getenv("RECALLSPECTION_API_URL", "http://localhost:8000")
ADMIN_KEY = os.getenv("RECALLSPECTION_ADMIN_KEY", "dev-admin-key")
DB_FILE = os.getenv("RECALLSPECTION_DB_FILE", "keys.db")
LOG_FILE = os.getenv("RECALLSPECTION_EXACT_LOG", "transparency.log")

# --- AUTH GATE ---
def check_password():
    if "password_correct" not in st.session_state:
        st.session_state["password_correct"] = False

    if not st.session_state["password_correct"]:
        st.title("🔒 Recallspection Admin")
        pwd = st.text_input("Enter Admin Password", type="password")
        if st.button("Login"):
            if pwd == ADMIN_KEY:
                st.session_state["password_correct"] = True
                st.rerun()
            else:
                st.error("Incorrect password")
        st.stop()

check_password()

# --- SIDEBAR ---
st.sidebar.title("🧠 Command Centre")
st.sidebar.markdown(f"**API:** `{API_BASE_URL}`")
st.sidebar.markdown(f"**DB:** `{DB_FILE}`")
if st.sidebar.button("Logout"):
    st.session_state["password_correct"] = False
    st.rerun()

page = st.sidebar.radio("Navigate", ["Overview", "API Keys", "Transparency Log", "Actions"])

# --- HELPERS ---
def get_db_connection():
    if not os.path.exists(DB_FILE):
        return None
    conn = sqlite3.connect(DB_FILE)
    conn.row_factory = sqlite3.Row
    return conn

def api_request(method, endpoint, json_data=None):
    try:
        headers = {"admin-key": ADMIN_KEY}
        if method == "GET":
            res = requests.get(f"{API_BASE_URL}{endpoint}", headers=headers, timeout=5)
        else:
            res = requests.post(f"{API_BASE_URL}{endpoint}", headers=headers, json=json_data, timeout=30)
        return res
    except Exception as e:
        st.error(f"API Connection Error: {e}")
        return None

# --- PAGES ---
if page == "Overview":
    st.title("📊 System Overview")
    
    # Live Health Check
    try:
        health = requests.get(f"{API_BASE_URL}/health", timeout=3).json()
        col1, col2, col3 = st.columns(3)
        col1.metric("API Status", health.get("status", "unknown").upper())
        col2.metric("SWSTM Facts", health.get("facts_swstm", 0))
        col3.metric("Exact Facts", health.get("facts_exact", 0))
        with st.expander("Raw Health Payload"):
            st.json(health)
    except:
        st.warning("Could not connect to live API. Showing offline DB stats only.")

    # DB Stats
    conn = get_db_connection()
    if conn:
        st.subheader("Database Stats")
        df = pd.read_sql_query("SELECT plan, COUNT(*) as count, SUM(usage) as total_usage FROM api_keys GROUP BY plan", conn)
        st.dataframe(df, use_container_width=True)
        conn.close()
    else:
        st.error(f"Database file not found at {DB_FILE}")

elif page == "API Keys":
    st.title("🔑 API Key Management")
    conn = get_db_connection()
    if conn:
        df = pd.read_sql_query("SELECT key_id, owner, plan, usage, `limit`, is_active, created_at FROM api_keys ORDER BY created_at DESC", conn)
        st.dataframe(df, use_container_width=True)
        
        st.subheader("Revoke Key")
        key_to_revoke = st.text_input("Enter key_id to revoke (e.g., rk_...)")
        if st.button("Revoke", type="primary"):
            res = api_request("POST", f"/admin/revoke/{key_to_revoke}")
            if res and res.status_code == 200:
                st.success(f"Revoked {key_to_revoke}")
                st.rerun()
            else:
                st.error(f"Failed: {res.text if res else 'No response'}")
        conn.close()
    else:
        st.error(f"Database file not found at {DB_FILE}")

elif page == "Transparency Log":
    st.title("📜 ExactMemory Transparency Log")
    st.caption("Hash-chained audit trail. Do not edit this file manually.")
    
    if os.path.exists(LOG_FILE):
        with open(LOG_FILE, 'r') as f:
            lines = f.readlines()
        
        # Show last 20 entries in reverse chronological order
        entries = []
        for line in reversed(lines[-20:]):
            try:
                entries.append(json.loads(line.strip()))
            except:
                pass
        
        if entries:
            st.dataframe(pd.DataFrame(entries), use_container_width=True)
        else:
            st.info("Log is empty.")
    else:
        st.warning(f"Log file not found at {LOG_FILE}. Add a fact to ExactMemory to generate it.")

elif page == "Actions":
    st.title("⚙️ Admin Actions")
    st.warning("These actions trigger heavy operations on the live API server.")
    
    col1, col2 = st.columns(2)
    with col1:
        if st.button("💾 Force Save Memory"):
            res = api_request("POST", "/admin/save")
            if res and res.status_code == 200:
                st.success("Memory flushed to disk.")
            else:
                st.error("Failed to save.")
                
    with col2:
        if st.button("🧠 Run Neural Consolidation"):
            with st.spinner("Consolidating SWSTM prototypes..."):
                res = api_request("POST", "/admin/consolidate")
                if res and res.status_code == 200:
                    st.success("Consolidation complete and saved.")
                else:
                    st.error("Failed to consolidate.")
